In [1]:
import numpy as np

In [2]:
range(10) # range is basically a generator function that generates data based on the steps mentioned

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
# generator functions can be created with a yield function

In [6]:
np.arange(.5,5.5)

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [7]:
np.arange(-5,-1)

array([-5, -4, -3, -2])

In [9]:
np.arange(-5,-1,-.5)

array([], dtype=float64)

In [17]:
list(np.linspace(1,5,5))

[1.0, 2.0, 3.0, 4.0, 5.0]

In [18]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros((3,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
np.empty((2,3))

array([[0., 1., 2.],
       [3., 4., 5.]])

In [32]:
np.eye(4) # this is called an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
a = np.eye(4)


In [34]:
a.shape

(4, 4)

In [35]:
a.size

16

In [37]:
a.ndim

2

In [38]:
a1 = np.random.rand(3,4)

In [39]:
a1

array([[0.48699406, 0.27289725, 0.49752712, 0.74491925],
       [0.3763021 , 0.87257127, 0.29147545, 0.24781343],
       [0.41384733, 0.96081822, 0.38790063, 0.00389223]])

In [40]:
import pandas as pd

In [41]:
pd.DataFrame(a1)

0         1         2         3
0  0.486994  0.272897  0.497527  0.744919
1  0.376302  0.872571  0.291475  0.247813
2  0.413847  0.960818  0.387901  0.003892

In [42]:
a1[1][1]

0.8725712711355377

In [45]:
a1[0:2,0:2]

array([[0.48699406, 0.27289725],
       [0.3763021 , 0.87257127]])

In [46]:
a1

array([[0.48699406, 0.27289725, 0.49752712, 0.74491925],
       [0.3763021 , 0.87257127, 0.29147545, 0.24781343],
       [0.41384733, 0.96081822, 0.38790063, 0.00389223]])

In [48]:
a1[[1,2],3]

array([0.24781343, 0.00389223])

In [61]:
m1 = np.random.randint(1,3, (3,3))

In [62]:
m1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [63]:
m2 = np.random.randint(2,4,(3,3))

In [64]:
m2

array([[2, 3, 2],
       [2, 3, 2],
       [3, 3, 3]])

In [65]:
m1*m2 # this only gives element wise multiplicaton for the two matrices

array([[2, 3, 4],
       [4, 6, 2],
       [3, 6, 3]])

In [67]:
m1@m2 # this multiplicaton of two matrices

array([[10, 12, 10],
       [11, 15, 11],
       [ 9, 12,  9]])

In [68]:
# the first rule of matrix multiplication is that the number of columns of the first matrix should always be equal to the number of rows of the second matrix
# the final dimenstion of the product matrix will be the row1 x column2

In [71]:
pow(m1@m2,2)

array([[100, 144, 100],
       [121, 225, 121],
       [ 81, 144,  81]])

In [72]:
np.sqrt(m1)

array([[1.        , 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [74]:
np.log10(m1)

array([[0.     , 0.     , 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.     , 0.30103, 0.     ]])

In [75]:
np.exp(m1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])